export default [
  {
     "flag":"https://restcountries.eu/data/afg.svg",
     "name":"Afghanistan",
     "region":"Asia",
     "population":27657145
  },
  {
     "flag":"https://restcountries.eu/data/ala.svg",
     "name":"Åland Islands",
     "region":"Europe",
     "population":28875
  },
  {
     "flag":"https://restcountries.eu/data/alb.svg",
     "name":"Albania",
     "region":"Europe",
     "population":2886026
  },
  {
     "flag":"https://restcountries.eu/data/dza.svg",
     "name":"Algeria",
     "region":"Africa",
     "population":40400000
  },
  {
     "flag":"https://restcountries.eu/data/asm.svg",
     "name":"American Samoa",
     "region":"Oceania",
     "population":57100
  },
  {
     "flag":"https://restcountries.eu/data/and.svg",
     "name":"Andorra",
     "region":"Europe",
     "population":78014
  },
  {
     "flag":"https://restcountries.eu/data/ago.svg",
     "name":"Angola",
     "region":"Africa",
     "population":25868000
  },
  {
     "flag":"https://restcountries.eu/data/aia.svg",
     "name":"Anguilla",
     "region":"Americas",
     "population":13452
  },
  {
     "flag":"https://restcountries.eu/data/ata.svg",
     "name":"Antarctica",
     "region":"Polar",
     "population":1000
  },
  {
     "flag":"https://restcountries.eu/data/atg.svg",
     "name":"Antigua and Barbuda",
     "region":"Americas",
     "population":86295
  },
  {
     "flag":"https://restcountries.eu/data/arg.svg",
     "name":"Argentina",
     "region":"Americas",
     "population":43590400
  },
  {
     "flag":"https://restcountries.eu/data/arm.svg",
     "name":"Armenia",
     "region":"Asia",
     "population":2994400
  },
  {
     "flag":"https://restcountries.eu/data/abw.svg",
     "name":"Aruba",
     "region":"Americas",
     "population":107394
  },
  {
     "flag":"https://restcountries.eu/data/aus.svg",
     "name":"Australia",
     "region":"Oceania",
     "population":24117360
  },
  {
     "flag":"https://restcountries.eu/data/aut.svg",
     "name":"Austria",
     "region":"Europe",
     "population":8725931
  },
  {
     "flag":"https://restcountries.eu/data/aze.svg",
     "name":"Azerbaijan",
     "region":"Asia",
     "population":9730500
  },
  {
     "flag":"https://restcountries.eu/data/bhs.svg",
     "name":"Bahamas",
     "region":"Americas",
     "population":378040
  },
  {
     "flag":"https://restcountries.eu/data/bhr.svg",
     "name":"Bahrain",
     "region":"Asia",
     "population":1404900
  },
  {
     "flag":"https://restcountries.eu/data/bgd.svg",
     "name":"Bangladesh",
     "region":"Asia",
     "population":161006790
  },
  {
     "flag":"https://restcountries.eu/data/brb.svg",
     "name":"Barbados",
     "region":"Americas",
     "population":285000
  },
  {
     "flag":"https://restcountries.eu/data/blr.svg",
     "name":"Belarus",
     "region":"Europe",
     "population":9498700
  },
  {
     "flag":"https://restcountries.eu/data/bel.svg",
     "name":"Belgium",
     "region":"Europe",
     "population":11319511
  },
  {
     "flag":"https://restcountries.eu/data/blz.svg",
     "name":"Belize",
     "region":"Americas",
     "population":370300
  },
  {
     "flag":"https://restcountries.eu/data/ben.svg",
     "name":"Benin",
     "region":"Africa",
     "population":10653654
  },
  {
     "flag":"https://restcountries.eu/data/bmu.svg",
     "name":"Bermuda",
     "region":"Americas",
     "population":61954
  },
  {
     "flag":"https://restcountries.eu/data/btn.svg",
     "name":"Bhutan",
     "region":"Asia",
     "population":775620
  },
  {
     "flag":"https://restcountries.eu/data/bol.svg",
     "name":"Bolivia (Plurinational State of)",
     "region":"Americas",
     "population":10985059
  },
  {
     "flag":"https://restcountries.eu/data/bes.svg",
     "name":"Bonaire, Sint Eustatius and Saba",
     "region":"Americas",
     "population":17408
  },
  {
     "flag":"https://restcountries.eu/data/bih.svg",
     "name":"Bosnia and Herzegovina",
     "region":"Europe",
     "population":3531159
  },
  {
     "flag":"https://restcountries.eu/data/bwa.svg",
     "name":"Botswana",
     "region":"Africa",
     "population":2141206
  },
  {
     "flag":"https://restcountries.eu/data/bvt.svg",
     "name":"Bouvet Island",
     "region":"",
     "population":0
  },
  {
     "flag":"https://restcountries.eu/data/bra.svg",
     "name":"Brazil",
     "region":"Americas",
     "population":206135893
  },
  {
     "flag":"https://restcountries.eu/data/iot.svg",
     "name":"British Indian Ocean Territory",
     "region":"Africa",
     "population":3000
  },
  {
     "flag":"https://restcountries.eu/data/umi.svg",
     "name":"United States Minor Outlying Islands",
     "region":"Americas",
     "population":300
  },
  {
     "flag":"https://restcountries.eu/data/vgb.svg",
     "name":"Virgin Islands (British)",
     "region":"Americas",
     "population":28514
  },
  {
     "flag":"https://restcountries.eu/data/vir.svg",
     "name":"Virgin Islands (U.S.)",
     "region":"Americas",
     "population":114743
  },
  {
     "flag":"https://restcountries.eu/data/brn.svg",
     "name":"Brunei Darussalam",
     "region":"Asia",
     "population":411900
  },
  {
     "flag":"https://restcountries.eu/data/bgr.svg",
     "name":"Bulgaria",
     "region":"Europe",
     "population":7153784
  },
  {
     "flag":"https://restcountries.eu/data/bfa.svg",
     "name":"Burkina Faso",
     "region":"Africa",
     "population":19034397
  },
  {
     "flag":"https://restcountries.eu/data/bdi.svg",
     "name":"Burundi",
     "region":"Africa",
     "population":10114505
  },
  {
     "flag":"https://restcountries.eu/data/khm.svg",
     "name":"Cambodia",
     "region":"Asia",
     "population":15626444
  },
  {
     "flag":"https://restcountries.eu/data/cmr.svg",
     "name":"Cameroon",
     "region":"Africa",
     "population":22709892
  },
  {
     "flag":"https://restcountries.eu/data/can.svg",
     "name":"Canada",
     "region":"Americas",
     "population":36155487
  },
  {
     "flag":"https://restcountries.eu/data/cpv.svg",
     "name":"Cabo Verde",
     "region":"Africa",
     "population":531239
  },
  {
     "flag":"https://restcountries.eu/data/cym.svg",
     "name":"Cayman Islands",
     "region":"Americas",
     "population":58238
  },
  {
     "flag":"https://restcountries.eu/data/caf.svg",
     "name":"Central African Republic",
     "region":"Africa",
     "population":4998000
  },
  {
     "flag":"https://restcountries.eu/data/tcd.svg",
     "name":"Chad",
     "region":"Africa",
     "population":14497000
  },
  {
     "flag":"https://restcountries.eu/data/chl.svg",
     "name":"Chile",
     "region":"Americas",
     "population":18191900
  },
  {
     "flag":"https://restcountries.eu/data/chn.svg",
     "name":"China",
     "region":"Asia",
     "population":1377422166
  },
  {
     "flag":"https://restcountries.eu/data/cxr.svg",
     "name":"Christmas Island",
     "region":"Oceania",
     "population":2072
  },
  {
     "flag":"https://restcountries.eu/data/cck.svg",
     "name":"Cocos (Keeling) Islands",
     "region":"Oceania",
     "population":550
  },
  {
     "flag":"https://restcountries.eu/data/col.svg",
     "name":"Colombia",
     "region":"Americas",
     "population":48759958
  },
  {
     "flag":"https://restcountries.eu/data/com.svg",
     "name":"Comoros",
     "region":"Africa",
     "population":806153
  },
  {
     "flag":"https://restcountries.eu/data/cog.svg",
     "name":"Congo",
     "region":"Africa",
     "population":4741000
  },
  {
     "flag":"https://restcountries.eu/data/cod.svg",
     "name":"Congo (Democratic Republic of the)",
     "region":"Africa",
     "population":85026000
  },
  {
     "flag":"https://restcountries.eu/data/cok.svg",
     "name":"Cook Islands",
     "region":"Oceania",
     "population":18100
  },
  {
     "flag":"https://restcountries.eu/data/cri.svg",
     "name":"Costa Rica",
     "region":"Americas",
     "population":4890379
  },
  {
     "flag":"https://restcountries.eu/data/hrv.svg",
     "name":"Croatia",
     "region":"Europe",
     "population":4190669
  },
  {
     "flag":"https://restcountries.eu/data/cub.svg",
     "name":"Cuba",
     "region":"Americas",
     "population":11239004
  },
  {
     "flag":"https://restcountries.eu/data/cuw.svg",
     "name":"Curaçao",
     "region":"Americas",
     "population":154843
  },
  {
     "flag":"https://restcountries.eu/data/cyp.svg",
     "name":"Cyprus",
     "region":"Europe",
     "population":847000
  },
  {
     "flag":"https://restcountries.eu/data/cze.svg",
     "name":"Czech Republic",
     "region":"Europe",
     "population":10558524
  },
  {
     "flag":"https://restcountries.eu/data/dnk.svg",
     "name":"Denmark",
     "region":"Europe",
     "population":5717014
  },
  {
     "flag":"https://restcountries.eu/data/dji.svg",
     "name":"Djibouti",
     "region":"Africa",
     "population":900000
  },
  {
     "flag":"https://restcountries.eu/data/dma.svg",
     "name":"Dominica",
     "region":"Americas",
     "population":71293
  },
  {
     "flag":"https://restcountries.eu/data/dom.svg",
     "name":"Dominican Republic",
     "region":"Americas",
     "population":10075045
  },
  {
     "flag":"https://restcountries.eu/data/ecu.svg",
     "name":"Ecuador",
     "region":"Americas",
     "population":16545799
  },
  {
     "flag":"https://restcountries.eu/data/egy.svg",
     "name":"Egypt",
     "region":"Africa",
     "population":91290000
  },
  {
     "flag":"https://restcountries.eu/data/slv.svg",
     "name":"El Salvador",
     "region":"Americas",
     "population":6520675
  },
  {
     "flag":"https://restcountries.eu/data/gnq.svg",
     "name":"Equatorial Guinea",
     "region":"Africa",
     "population":1222442
  },
  {
     "flag":"https://restcountries.eu/data/eri.svg",
     "name":"Eritrea",
     "region":"Africa",
     "population":5352000
  },
  {
     "flag":"https://restcountries.eu/data/est.svg",
     "name":"Estonia",
     "region":"Europe",
     "population":1315944
  },
  {
     "flag":"https://restcountries.eu/data/eth.svg",
     "name":"Ethiopia",
     "region":"Africa",
     "population":92206005
  },
  {
     "flag":"https://restcountries.eu/data/flk.svg",
     "name":"Falkland Islands (Malvinas)",
     "region":"Americas",
     "population":2563
  },
  {
     "flag":"https://restcountries.eu/data/fro.svg",
     "name":"Faroe Islands",
     "region":"Europe",
     "population":49376
  },
  {
     "flag":"https://restcountries.eu/data/fji.svg",
     "name":"Fiji",
     "region":"Oceania",
     "population":867000
  },
  {
     "flag":"https://restcountries.eu/data/fin.svg",
     "name":"Finland",
     "region":"Europe",
     "population":5491817
  },
  {
     "flag":"https://restcountries.eu/data/fra.svg",
     "name":"France",
     "region":"Europe",
     "population":66710000
  },
  {
     "flag":"https://restcountries.eu/data/guf.svg",
     "name":"French Guiana",
     "region":"Americas",
     "population":254541
  },
  {
     "flag":"https://restcountries.eu/data/pyf.svg",
     "name":"French Polynesia",
     "region":"Oceania",
     "population":271800
  },
  {
     "flag":"https://restcountries.eu/data/atf.svg",
     "name":"French Southern Territories",
     "region":"Africa",
     "population":140
  },
  {
     "flag":"https://restcountries.eu/data/gab.svg",
     "name":"Gabon",
     "region":"Africa",
     "population":1802278
  },
  {
     "flag":"https://restcountries.eu/data/gmb.svg",
     "name":"Gambia",
     "region":"Africa",
     "population":1882450
  },
  {
     "flag":"https://restcountries.eu/data/geo.svg",
     "name":"Georgia",
     "region":"Asia",
     "population":3720400
  },
  {
     "flag":"https://restcountries.eu/data/deu.svg",
     "name":"Germany",
     "region":"Europe",
     "population":81770900
  },
  {
     "flag":"https://restcountries.eu/data/gha.svg",
     "name":"Ghana",
     "region":"Africa",
     "population":27670174
  },
  {
     "flag":"https://restcountries.eu/data/gib.svg",
     "name":"Gibraltar",
     "region":"Europe",
     "population":33140
  },
  {
     "flag":"https://restcountries.eu/data/grc.svg",
     "name":"Greece",
     "region":"Europe",
     "population":10858018
  },
  {
     "flag":"https://restcountries.eu/data/grl.svg",
     "name":"Greenland",
     "region":"Americas",
     "population":55847
  },
  {
     "flag":"https://restcountries.eu/data/grd.svg",
     "name":"Grenada",
     "region":"Americas",
     "population":103328
  },
  {
     "flag":"https://restcountries.eu/data/glp.svg",
     "name":"Guadeloupe",
     "region":"Americas",
     "population":400132
  },
  {
     "flag":"https://restcountries.eu/data/gum.svg",
     "name":"Guam",
     "region":"Oceania",
     "population":184200
  },
  {
     "flag":"https://restcountries.eu/data/gtm.svg",
     "name":"Guatemala",
     "region":"Americas",
     "population":16176133
  },
  {
     "flag":"https://restcountries.eu/data/ggy.svg",
     "name":"Guernsey",
     "region":"Europe",
     "population":62999
  },
  {
     "flag":"https://restcountries.eu/data/gin.svg",
     "name":"Guinea",
     "region":"Africa",
     "population":12947000
  },
  {
     "flag":"https://restcountries.eu/data/gnb.svg",
     "name":"Guinea-Bissau",
     "region":"Africa",
     "population":1547777
  },
  {
     "flag":"https://restcountries.eu/data/guy.svg",
     "name":"Guyana",
     "region":"Americas",
     "population":746900
  },
  {
     "flag":"https://restcountries.eu/data/hti.svg",
     "name":"Haiti",
     "region":"Americas",
     "population":11078033
  },
  {
     "flag":"https://restcountries.eu/data/hmd.svg",
     "name":"Heard Island and McDonald Islands",
     "region":"",
     "population":0
  },
  {
     "flag":"https://restcountries.eu/data/vat.svg",
     "name":"Holy See",
     "region":"Europe",
     "population":451
  },
  {
     "flag":"https://restcountries.eu/data/hnd.svg",
     "name":"Honduras",
     "region":"Americas",
     "population":8576532
  },
  {
     "flag":"https://restcountries.eu/data/hkg.svg",
     "name":"Hong Kong",
     "region":"Asia",
     "population":7324300
  },
  {
     "flag":"https://restcountries.eu/data/hun.svg",
     "name":"Hungary",
     "region":"Europe",
     "population":9823000
  },
  {
     "flag":"https://restcountries.eu/data/isl.svg",
     "name":"Iceland",
     "region":"Europe",
     "population":334300
  },
  {
     "flag":"https://restcountries.eu/data/ind.svg",
     "name":"India",
     "region":"Asia",
     "population":1295210000
  },
  {
     "flag":"https://restcountries.eu/data/idn.svg",
     "name":"Indonesia",
     "region":"Asia",
     "population":258705000
  },
  {
     "flag":"https://restcountries.eu/data/civ.svg",
     "name":"Côte d'Ivoire",
     "region":"Africa",
     "population":22671331
  },
  {
     "flag":"https://restcountries.eu/data/irn.svg",
     "name":"Iran (Islamic Republic of)",
     "region":"Asia",
     "population":79369900
  },
  {
     "flag":"https://restcountries.eu/data/irq.svg",
     "name":"Iraq",
     "region":"Asia",
     "population":37883543
  },
  {
     "flag":"https://restcountries.eu/data/irl.svg",
     "name":"Ireland",
     "region":"Europe",
     "population":6378000
  },
  {
     "flag":"https://restcountries.eu/data/imn.svg",
     "name":"Isle of Man",
     "region":"Europe",
     "population":84497
  },
  {
     "flag":"https://restcountries.eu/data/isr.svg",
     "name":"Israel",
     "region":"Asia",
     "population":8527400
  },
  {
     "flag":"https://restcountries.eu/data/ita.svg",
     "name":"Italy",
     "region":"Europe",
     "population":60665551
  },
  {
     "flag":"https://restcountries.eu/data/jam.svg",
     "name":"Jamaica",
     "region":"Americas",
     "population":2723246
  },
  {
     "flag":"https://restcountries.eu/data/jpn.svg",
     "name":"Japan",
     "region":"Asia",
     "population":126960000
  },
  {
     "flag":"https://restcountries.eu/data/jey.svg",
     "name":"Jersey",
     "region":"Europe",
     "population":100800
  },
  {
     "flag":"https://restcountries.eu/data/jor.svg",
     "name":"Jordan",
     "region":"Asia",
     "population":9531712
  },
  {
     "flag":"https://restcountries.eu/data/kaz.svg",
     "name":"Kazakhstan",
     "region":"Asia",
     "population":17753200
  },
  {
     "flag":"https://restcountries.eu/data/ken.svg",
     "name":"Kenya",
     "region":"Africa",
     "population":47251000
  },
  {
     "flag":"https://restcountries.eu/data/kir.svg",
     "name":"Kiribati",
     "region":"Oceania",
     "population":113400
  },
  {
     "flag":"https://restcountries.eu/data/kwt.svg",
     "name":"Kuwait",
     "region":"Asia",
     "population":4183658
  },
  {
     "flag":"https://restcountries.eu/data/kgz.svg",
     "name":"Kyrgyzstan",
     "region":"Asia",
     "population":6047800
  },
  {
     "flag":"https://restcountries.eu/data/lao.svg",
     "name":"Lao People's Democratic Republic",
     "region":"Asia",
     "population":6492400
  },
  {
     "flag":"https://restcountries.eu/data/lva.svg",
     "name":"Latvia",
     "region":"Europe",
     "population":1961600
  },
  {
     "flag":"https://restcountries.eu/data/lbn.svg",
     "name":"Lebanon",
     "region":"Asia",
     "population":5988000
  },
  {
     "flag":"https://restcountries.eu/data/lso.svg",
     "name":"Lesotho",
     "region":"Africa",
     "population":1894194
  },
  {
     "flag":"https://restcountries.eu/data/lbr.svg",
     "name":"Liberia",
     "region":"Africa",
     "population":4615000
  },
  {
     "flag":"https://restcountries.eu/data/lby.svg",
     "name":"Libya",
     "region":"Africa",
     "population":6385000
  },
  {
     "flag":"https://restcountries.eu/data/lie.svg",
     "name":"Liechtenstein",
     "region":"Europe",
     "population":37623
  },
  {
     "flag":"https://restcountries.eu/data/ltu.svg",
     "name":"Lithuania",
     "region":"Europe",
     "population":2872294
  },
  {
     "flag":"https://restcountries.eu/data/lux.svg",
     "name":"Luxembourg",
     "region":"Europe",
     "population":576200
  },
  {
     "flag":"https://restcountries.eu/data/mac.svg",
     "name":"Macao",
     "region":"Asia",
     "population":649100
  },
  {
     "flag":"https://restcountries.eu/data/mkd.svg",
     "name":"Macedonia (the former Yugoslav Republic of)",
     "region":"Europe",
     "population":2058539
  },
  {
     "flag":"https://restcountries.eu/data/mdg.svg",
     "name":"Madagascar",
     "region":"Africa",
     "population":22434363
  },
  {
     "flag":"https://restcountries.eu/data/mwi.svg",
     "name":"Malawi",
     "region":"Africa",
     "population":16832910
  },
  {
     "flag":"https://restcountries.eu/data/mys.svg",
     "name":"Malaysia",
     "region":"Asia",
     "population":31405416
  },
  {
     "flag":"https://restcountries.eu/data/mdv.svg",
     "name":"Maldives",
     "region":"Asia",
     "population":344023
  },
  {
     "flag":"https://restcountries.eu/data/mli.svg",
     "name":"Mali",
     "region":"Africa",
     "population":18135000
  },
  {
     "flag":"https://restcountries.eu/data/mlt.svg",
     "name":"Malta",
     "region":"Europe",
     "population":425384
  },
  {
     "flag":"https://restcountries.eu/data/mhl.svg",
     "name":"Marshall Islands",
     "region":"Oceania",
     "population":54880
  },
  {
     "flag":"https://restcountries.eu/data/mtq.svg",
     "name":"Martinique",
     "region":"Americas",
     "population":378243
  },
  {
     "flag":"https://restcountries.eu/data/mrt.svg",
     "name":"Mauritania",
     "region":"Africa",
     "population":3718678
  },
  {
     "flag":"https://restcountries.eu/data/mus.svg",
     "name":"Mauritius",
     "region":"Africa",
     "population":1262879
  },
  {
     "flag":"https://restcountries.eu/data/myt.svg",
     "name":"Mayotte",
     "region":"Africa",
     "population":226915
  },
  {
     "flag":"https://restcountries.eu/data/mex.svg",
     "name":"Mexico",
     "region":"Americas",
     "population":122273473
  },
  {
     "flag":"https://restcountries.eu/data/fsm.svg",
     "name":"Micronesia (Federated States of)",
     "region":"Oceania",
     "population":102800
  },
  {
     "flag":"https://restcountries.eu/data/mda.svg",
     "name":"Moldova (Republic of)",
     "region":"Europe",
     "population":3553100
  },
  {
     "flag":"https://restcountries.eu/data/mco.svg",
     "name":"Monaco",
     "region":"Europe",
     "population":38400
  },
  {
     "flag":"https://restcountries.eu/data/mng.svg",
     "name":"Mongolia",
     "region":"Asia",
     "population":3093100
  },
  {
     "flag":"https://restcountries.eu/data/mne.svg",
     "name":"Montenegro",
     "region":"Europe",
     "population":621810
  },
  {
     "flag":"https://restcountries.eu/data/msr.svg",
     "name":"Montserrat",
     "region":"Americas",
     "population":4922
  },
  {
     "flag":"https://restcountries.eu/data/mar.svg",
     "name":"Morocco",
     "region":"Africa",
     "population":33337529
  },
  {
     "flag":"https://restcountries.eu/data/moz.svg",
     "name":"Mozambique",
     "region":"Africa",
     "population":26423700
  },
  {
     "flag":"https://restcountries.eu/data/mmr.svg",
     "name":"Myanmar",
     "region":"Asia",
     "population":51419420
  },
  {
     "flag":"https://restcountries.eu/data/nam.svg",
     "name":"Namibia",
     "region":"Africa",
     "population":2324388
  },
  {
     "flag":"https://restcountries.eu/data/nru.svg",
     "name":"Nauru",
     "region":"Oceania",
     "population":10084
  },
  {
     "flag":"https://restcountries.eu/data/npl.svg",
     "name":"Nepal",
     "region":"Asia",
     "population":28431500
  },
  {
     "flag":"https://restcountries.eu/data/nld.svg",
     "name":"Netherlands",
     "region":"Europe",
     "population":17019800
  },
  {
     "flag":"https://restcountries.eu/data/ncl.svg",
     "name":"New Caledonia",
     "region":"Oceania",
     "population":268767
  },
  {
     "flag":"https://restcountries.eu/data/nzl.svg",
     "name":"New Zealand",
     "region":"Oceania",
     "population":4697854
  },
  {
     "flag":"https://restcountries.eu/data/nic.svg",
     "name":"Nicaragua",
     "region":"Americas",
     "population":6262703
  },
  {
     "flag":"https://restcountries.eu/data/ner.svg",
     "name":"Niger",
     "region":"Africa",
     "population":20715000
  },
  {
     "flag":"https://restcountries.eu/data/nga.svg",
     "name":"Nigeria",
     "region":"Africa",
     "population":186988000
  },
  {
     "flag":"https://restcountries.eu/data/niu.svg",
     "name":"Niue",
     "region":"Oceania",
     "population":1470
  },
  {
     "flag":"https://restcountries.eu/data/nfk.svg",
     "name":"Norfolk Island",
     "region":"Oceania",
     "population":2302
  },
  {
     "flag":"https://restcountries.eu/data/prk.svg",
     "name":"Korea (Democratic People's Republic of)",
     "region":"Asia",
     "population":25281000
  },
  {
     "flag":"https://restcountries.eu/data/mnp.svg",
     "name":"Northern Mariana Islands",
     "region":"Oceania",
     "population":56940
  },
  {
     "flag":"https://restcountries.eu/data/nor.svg",
     "name":"Norway",
     "region":"Europe",
     "population":5223256
  },
  {
     "flag":"https://restcountries.eu/data/omn.svg",
     "name":"Oman",
     "region":"Asia",
     "population":4420133
  },
  {
     "flag":"https://restcountries.eu/data/pak.svg",
     "name":"Pakistan",
     "region":"Asia",
     "population":194125062
  },
  {
     "flag":"https://restcountries.eu/data/plw.svg",
     "name":"Palau",
     "region":"Oceania",
     "population":17950
  },
  {
     "flag":"https://restcountries.eu/data/pse.svg",
     "name":"Palestine, State of",
     "region":"Asia",
     "population":4682467
  },
  {
     "flag":"https://restcountries.eu/data/pan.svg",
     "name":"Panama",
     "region":"Americas",
     "population":3814672
  },
  {
     "flag":"https://restcountries.eu/data/png.svg",
     "name":"Papua New Guinea",
     "region":"Oceania",
     "population":8083700
  },
  {
     "flag":"https://restcountries.eu/data/pry.svg",
     "name":"Paraguay",
     "region":"Americas",
     "population":6854536
  },
  {
     "flag":"https://restcountries.eu/data/per.svg",
     "name":"Peru",
     "region":"Americas",
     "population":31488700
  },
  {
     "flag":"https://restcountries.eu/data/phl.svg",
     "name":"Philippines",
     "region":"Asia",
     "population":103279800
  },
  {
     "flag":"https://restcountries.eu/data/pcn.svg",
     "name":"Pitcairn",
     "region":"Oceania",
     "population":56
  },
  {
     "flag":"https://restcountries.eu/data/pol.svg",
     "name":"Poland",
     "region":"Europe",
     "population":38437239
  },
  {
     "flag":"https://restcountries.eu/data/prt.svg",
     "name":"Portugal",
     "region":"Europe",
     "population":10374822
  },
  {
     "flag":"https://restcountries.eu/data/pri.svg",
     "name":"Puerto Rico",
     "region":"Americas",
     "population":3474182
  },
  {
     "flag":"https://restcountries.eu/data/qat.svg",
     "name":"Qatar",
     "region":"Asia",
     "population":2587564
  },
  {
     "flag":"https://restcountries.eu/data/kos.svg",
     "name":"Republic of Kosovo",
     "region":"Europe",
     "population":1733842
  },
  {
     "flag":"https://restcountries.eu/data/reu.svg",
     "name":"Réunion",
     "region":"Africa",
     "population":840974
  },
  {
     "flag":"https://restcountries.eu/data/rou.svg",
     "name":"Romania",
     "region":"Europe",
     "population":19861408
  },
  {
     "flag":"https://restcountries.eu/data/rus.svg",
     "name":"Russian Federation",
     "region":"Europe",
     "population":146599183
  },
  {
     "flag":"https://restcountries.eu/data/rwa.svg",
     "name":"Rwanda",
     "region":"Africa",
     "population":11553188
  },
  {
     "flag":"https://restcountries.eu/data/blm.svg",
     "name":"Saint Barthélemy",
     "region":"Americas",
     "population":9417
  },
  {
     "flag":"https://restcountries.eu/data/shn.svg",
     "name":"Saint Helena, Ascension and Tristan da Cunha",
     "region":"Africa",
     "population":4255
  },
  {
     "flag":"https://restcountries.eu/data/kna.svg",
     "name":"Saint Kitts and Nevis",
     "region":"Americas",
     "population":46204
  },
  {
     "flag":"https://restcountries.eu/data/lca.svg",
     "name":"Saint Lucia",
     "region":"Americas",
     "population":186000
  },
  {
     "flag":"https://restcountries.eu/data/maf.svg",
     "name":"Saint Martin (French part)",
     "region":"Americas",
     "population":36979
  },
  {
     "flag":"https://restcountries.eu/data/spm.svg",
     "name":"Saint Pierre and Miquelon",
     "region":"Americas",
     "population":6069
  },
  {
     "flag":"https://restcountries.eu/data/vct.svg",
     "name":"Saint Vincent and the Grenadines",
     "region":"Americas",
     "population":109991
  },
  {
     "flag":"https://restcountries.eu/data/wsm.svg",
     "name":"Samoa",
     "region":"Oceania",
     "population":194899
  },
  {
     "flag":"https://restcountries.eu/data/smr.svg",
     "name":"San Marino",
     "region":"Europe",
     "population":33005
  },
  {
     "flag":"https://restcountries.eu/data/stp.svg",
     "name":"Sao Tome and Principe",
     "region":"Africa",
     "population":187356
  },
  {
     "flag":"https://restcountries.eu/data/sau.svg",
     "name":"Saudi Arabia",
     "region":"Asia",
     "population":32248200
  },
  {
     "flag":"https://restcountries.eu/data/sen.svg",
     "name":"Senegal",
     "region":"Africa",
     "population":14799859
  },
  {
     "flag":"https://restcountries.eu/data/srb.svg",
     "name":"Serbia",
     "region":"Europe",
     "population":7076372
  },
  {
     "flag":"https://restcountries.eu/data/syc.svg",
     "name":"Seychelles",
     "region":"Africa",
     "population":91400
  },
  {
     "flag":"https://restcountries.eu/data/sle.svg",
     "name":"Sierra Leone",
     "region":"Africa",
     "population":7075641
  },
  {
     "flag":"https://restcountries.eu/data/sgp.svg",
     "name":"Singapore",
     "region":"Asia",
     "population":5535000
  },
  {
     "flag":"https://restcountries.eu/data/sxm.svg",
     "name":"Sint Maarten (Dutch part)",
     "region":"Americas",
     "population":38247
  },
  {
     "flag":"https://restcountries.eu/data/svk.svg",
     "name":"Slovakia",
     "region":"Europe",
     "population":5426252
  },
  {
     "flag":"https://restcountries.eu/data/svn.svg",
     "name":"Slovenia",
     "region":"Europe",
     "population":2064188
  },
  {
     "flag":"https://restcountries.eu/data/slb.svg",
     "name":"Solomon Islands",
     "region":"Oceania",
     "population":642000
  },
  {
     "flag":"https://restcountries.eu/data/som.svg",
     "name":"Somalia",
     "region":"Africa",
     "population":11079000
  },
  {
     "flag":"https://restcountries.eu/data/zaf.svg",
     "name":"South Africa",
     "region":"Africa",
     "population":55653654
  },
  {
     "flag":"https://restcountries.eu/data/sgs.svg",
     "name":"South Georgia and the South Sandwich Islands",
     "region":"Americas",
     "population":30
  },
  {
     "flag":"https://restcountries.eu/data/kor.svg",
     "name":"Korea (Republic of)",
     "region":"Asia",
     "population":50801405
  },
  {
     "flag":"https://restcountries.eu/data/ssd.svg",
     "name":"South Sudan",
     "region":"Africa",
     "population":12131000
  },
  {
     "flag":"https://restcountries.eu/data/esp.svg",
     "name":"Spain",
     "region":"Europe",
     "population":46438422
  },
  {
     "flag":"https://restcountries.eu/data/lka.svg",
     "name":"Sri Lanka",
     "region":"Asia",
     "population":20966000
  },
  {
     "flag":"https://restcountries.eu/data/sdn.svg",
     "name":"Sudan",
     "region":"Africa",
     "population":39598700
  },
  {
     "flag":"https://restcountries.eu/data/sur.svg",
     "name":"Suriname",
     "region":"Americas",
     "population":541638
  },
  {
     "flag":"https://restcountries.eu/data/sjm.svg",
     "name":"Svalbard and Jan Mayen",
     "region":"Europe",
     "population":2562
  },
  {
     "flag":"https://restcountries.eu/data/swz.svg",
     "name":"Swaziland",
     "region":"Africa",
     "population":1132657
  },
  {
     "flag":"https://restcountries.eu/data/swe.svg",
     "name":"Sweden",
     "region":"Europe",
     "population":9894888
  },
  {
     "flag":"https://restcountries.eu/data/che.svg",
     "name":"Switzerland",
     "region":"Europe",
     "population":8341600
  },
  {
     "flag":"https://restcountries.eu/data/syr.svg",
     "name":"Syrian Arab Republic",
     "region":"Asia",
     "population":18564000
  },
  {
     "flag":"https://restcountries.eu/data/twn.svg",
     "name":"Taiwan",
     "region":"Asia",
     "population":23503349
  },
  {
     "flag":"https://restcountries.eu/data/tjk.svg",
     "name":"Tajikistan",
     "region":"Asia",
     "population":8593600
  },
  {
     "flag":"https://restcountries.eu/data/tza.svg",
     "name":"Tanzania, United Republic of",
     "region":"Africa",
     "population":55155000
  },
  {
     "flag":"https://restcountries.eu/data/tha.svg",
     "name":"Thailand",
     "region":"Asia",
     "population":65327652
  },
  {
     "flag":"https://restcountries.eu/data/tls.svg",
     "name":"Timor-Leste",
     "region":"Asia",
     "population":1167242
  },
  {
     "flag":"https://restcountries.eu/data/tgo.svg",
     "name":"Togo",
     "region":"Africa",
     "population":7143000
  },
  {
     "flag":"https://restcountries.eu/data/tkl.svg",
     "name":"Tokelau",
     "region":"Oceania",
     "population":1411
  },
  {
     "flag":"https://restcountries.eu/data/ton.svg",
     "name":"Tonga",
     "region":"Oceania",
     "population":103252
  },
  {
     "flag":"https://restcountries.eu/data/tto.svg",
     "name":"Trinidad and Tobago",
     "region":"Americas",
     "population":1349667
  },
  {
     "flag":"https://restcountries.eu/data/tun.svg",
     "name":"Tunisia",
     "region":"Africa",
     "population":11154400
  },
  {
     "flag":"https://restcountries.eu/data/tur.svg",
     "name":"Turkey",
     "region":"Asia",
     "population":78741053
  },
  {
     "flag":"https://restcountries.eu/data/tkm.svg",
     "name":"Turkmenistan",
     "region":"Asia",
     "population":4751120
  },
  {
     "flag":"https://restcountries.eu/data/tca.svg",
     "name":"Turks and Caicos Islands",
     "region":"Americas",
     "population":31458
  },
  {
     "flag":"https://restcountries.eu/data/tuv.svg",
     "name":"Tuvalu",
     "region":"Oceania",
     "population":10640
  },
  {
     "flag":"https://restcountries.eu/data/uga.svg",
     "name":"Uganda",
     "region":"Africa",
     "population":33860700
  },
  {
     "flag":"https://restcountries.eu/data/ukr.svg",
     "name":"Ukraine",
     "region":"Europe",
     "population":42692393
  },
  {
     "flag":"https://restcountries.eu/data/are.svg",
     "name":"United Arab Emirates",
     "region":"Asia",
     "population":9856000
  },
  {
     "flag":"https://restcountries.eu/data/gbr.svg",
     "name":"United Kingdom of Great Britain and Northern Ireland",
     "region":"Europe",
     "population":65110000
  },
  {
     "flag":"https://restcountries.eu/data/usa.svg",
     "name":"United States of America",
     "region":"Americas",
     "population":323947000
  },
  {
     "flag":"https://restcountries.eu/data/ury.svg",
     "name":"Uruguay",
     "region":"Americas",
     "population":3480222
  },
  {
     "flag":"https://restcountries.eu/data/uzb.svg",
     "name":"Uzbekistan",
     "region":"Asia",
     "population":31576400
  },
  {
     "flag":"https://restcountries.eu/data/vut.svg",
     "name":"Vanuatu",
     "region":"Oceania",
     "population":277500
  },
  {
     "flag":"https://restcountries.eu/data/ven.svg",
     "name":"Venezuela (Bolivarian Republic of)",
     "region":"Americas",
     "population":31028700
  },
  {
     "flag":"https://restcountries.eu/data/vnm.svg",
     "name":"Viet Nam",
     "region":"Asia",
     "population":92700000
  },
  {
     "flag":"https://restcountries.eu/data/wlf.svg",
     "name":"Wallis and Futuna",
     "region":"Oceania",
     "population":11750
  },
  {
     "flag":"https://restcountries.eu/data/esh.svg",
     "name":"Western Sahara",
     "region":"Africa",
     "population":510713
  },
  {
     "flag":"https://restcountries.eu/data/yem.svg",
     "name":"Yemen",
     "region":"Asia",
     "population":27478000
  },
  {
     "flag":"https://restcountries.eu/data/zmb.svg",
     "name":"Zambia",
     "region":"Africa",
     "population":15933883
  },
  {
     "flag":"https://restcountries.eu/data/zwe.svg",
     "name":"Zimbabwe",
     "region":"Africa",
     "population":14240168
  }
]
